version: "3"

services:
  richo.tw:
    build: .
    container_name: richo.tw
    volumes:
       - .:/home/richo.tw
    command: uwsgi --ini app.ini
    networks:
      - web_nw
    environment:
      - TZ=Asia/Taipei
    depends_on:
      - ghost

  ghost:
    image: ghost:latest
    container_name: ghost
    restart: always
    networks:
      - web_nw
    ports:
      - 2368:2368
    volumes:
      - ./content:/var/lib/ghost/content
      - ./ghost/config.development.json:/var/lib/ghost/config.development.json
    environment:
      - NODE_ENV=development

  web_server:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./conf.d/richo.tw.dev.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx
    networks:
      - web_nw
    ports:
      - 80:80
    environment:
      - TZ=Asia/Taipei
    depends_on:
      - richo.tw

networks:
  web_nw:
    driver: bridge
